# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: project_node.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='project_node.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x12project_node.proto\"L\n\x0bProjectNode\x12\x14\n\x0cproject_name\x18\x01 \x01(\t\x12\x13\n\x0bpublic_keys\x18\x02 \x03(\t\x12\x12\n\ntask_names\x18\x03 \x03(\t\"5\n\x14ProjectNodeContainer\x12\x1d\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0c.ProjectNodeb\x06proto3')
)




_PROJECTNODE = _descriptor.Descriptor(
  name='ProjectNode',
  full_name='ProjectNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_name', full_name='ProjectNode.project_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='public_keys', full_name='ProjectNode.public_keys', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_names', full_name='ProjectNode.task_names', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=98,
)


_PROJECTNODECONTAINER = _descriptor.Descriptor(
  name='ProjectNodeContainer',
  full_name='ProjectNodeContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='ProjectNodeContainer.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=153,
)

_PROJECTNODECONTAINER.fields_by_name['entries'].message_type = _PROJECTNODE
DESCRIPTOR.message_types_by_name['ProjectNode'] = _PROJECTNODE
DESCRIPTOR.message_types_by_name['ProjectNodeContainer'] = _PROJECTNODECONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProjectNode = _reflection.GeneratedProtocolMessageType('ProjectNode', (_message.Message,), dict(
  DESCRIPTOR = _PROJECTNODE,
  __module__ = 'project_node_pb2'
  # @@protoc_insertion_point(class_scope:ProjectNode)
  ))
_sym_db.RegisterMessage(ProjectNode)

ProjectNodeContainer = _reflection.GeneratedProtocolMessageType('ProjectNodeContainer', (_message.Message,), dict(
  DESCRIPTOR = _PROJECTNODECONTAINER,
  __module__ = 'project_node_pb2'
  # @@protoc_insertion_point(class_scope:ProjectNodeContainer)
  ))
_sym_db.RegisterMessage(ProjectNodeContainer)


# @@protoc_insertion_point(module_scope)
